<ul class="list_style_none">
    <li>
        <a href="/post/add" data-toggle="modal" data-target="#new_post_modal"><?php echo $t->_("Write Post"); ?></a>
    </li>
    <li>
        <a href="/post/mypage_index"><?php echo $t->_("Manage Post"); ?></a>
    </li>
    <li>
        <a href="/post/mypage_index"><?php echo $t->_("Category"); ?></a>
    </li>
    <li>
        <a href="/post/mypage_index"><?php echo $t->_("Sub Category"); ?></a>
    </li>
</ul>