<!-- モーダルウィンドウセクション -->
<!-- 新規投稿モーダル -->
<div class="modal fade" id="new_post_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><?php echo $t->_("New Post"); ?></h5>
      </div>
      <div class="modal-body">
        <!-- <form action="/post/add" method="POST"> -->
        <div class="form-group">
            <label for="title"><?php echo $t->_("Title"); ?></label>
            <input type="text" name="title" id="title" class="form-control form_title" placeholder="<?php echo $t->_("Title"); ?>">
        </div>
        <div class="form-group">
            <label for="body"><?php echo $t->_("Body"); ?></label>
            <textarea name="body" id="body" rows="6" cols="30" class="form-control form_body" placeholder="<?php echo $t->_("Body"); ?>"></textarea>
        </div>
        

        <!-- </form> -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo $t->_('Close'); ?></button>
        <button type="button" class="btn btn-primary" id="add_post"><?php echo $t->_('Post'); ?></button>
      </div>
    </div>
  </div>
</div>

<!-- 記事編集モーダル -->


<!-- 記事表示部 -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2 bg-gray">
            <?php $this->partial("partial/sidebar_mypage"); ?>
        </div>

        <div class="col-sm-10">
            <div class="border-b mb-5">
                <h2><?php echo $t->_('Post Management'); ?></h2>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th><?php echo $t->_('Title'); ?></th>
                        <th><?php echo $t->_('Edit'); ?></th>
                        <th><?php echo $t->_('Category'); ?></th>
                        <th><?php echo $t->_('SubCategory'); ?></th>
                        <th><?php echo $t->_('Created'); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($posts as $post): ?>
                        <tr>
                            <td><?php echo $post->title; ?></td>
                            <td></td>
                            <td><?php echo $posts->category_id; ?></td>
                            <td><?php echo $posts->sub_category_id; ?></td>
                            <td><?php echo $posts->created; ?></td>
                        </tr>
                    <?php endforeach; ?>                    
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="/public/js/mypage_index.js"></script>

