<!-- モーダルウィンドウセクション -->
<!-- 新規投稿モーダル -->
<div class="modal fade" id="new_post_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><?php echo $t->_("New Post"); ?></h5>
      </div>
      <div class="modal-body">
        <form class="modal_form">        
          <?php $this->partial('partial/post_modal_form'); ?>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo $t->_('Close'); ?></button>
        <button type="button" class="btn btn-primary" id="add_post"><?php echo $t->_('Post'); ?></button>
      </div>
    </div>
  </div>
</div>

<!-- 記事編集モーダル -->
<div class="modal fade" id="edit_post_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><?php echo $t->_("Edit Post"); ?></h5>
      </div>
      <div class="modal-body">
        <form class="modal_form">
          <!-- id(非表示フォーム) -->
          <input type="hidden" name="id" id="id" class="form-control form_id">
          <?php $this->partial('partial/post_modal_form'); ?>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo $t->_('Close'); ?></button>
        <button type="button" class="btn btn-primary" id="edit_post"><?php echo $t->_('Save'); ?></button>
      </div>
    </div>
  </div>
</div>

<!-- 記事表示部 -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2 bg-gray pt-3 pl-4">
            <!-- partial()は、PhalconのViewクラスに用意されているメソッド -->
            <?php $this->partial("partial/sidebar_mypage"); ?>
        </div>

        <div class="col-sm-10">
            <div class="border-b mb-5">
                <h2><?php echo $t->_('Post Management'); ?></h2>
            </div>
            <table id="post_table" class="table">
                <thead>
                    <tr>
                        <th><?php echo $t->_('Title'); ?></th>
                        <th><?php echo $t->_('Edit'); ?></th>
                        <th><?php echo $t->_('Category'); ?></th>
                        <th><?php echo $t->_('SubCategory'); ?></th>
                        <th><?php echo $t->_('Created'); ?></th>
                        <!-- 記事編集モーダル用データ -->
                        <th class="d-none"><?php echo $t->_('Id'); ?></th>
                        <th class="d-none"><?php echo $t->_('Body'); ?></th>
                        <th class="d-none"><?php echo $t->_('Category Id'); ?></th>
                        <th class="d-none"><?php echo $t->_('SubCategory Id'); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($posts as $post): ?>
                        <tr>
                            <td class="title"><?php echo $post->title; ?></td>
                            <td>
                                <button data-toggle="modal" data-target="#edit_post_modal" id="<?php echo $post->id; ?>" class="edit_post btn btn-primary btn-xs">
                                    <?php echo $t->_('Edit'); ?>
                                </button>
                            </td>
                            <td><?php echo $post->getCategories()->category_name; ?></td>
                            <td><?php echo $post->getSubCategories()->sub_category_name; ?></td>
                            <td><?php echo $post->created; ?></td>
                            <!-- 記事編集モーダル用データ -->
                            <td class="d-none hidden_id"><?php echo $post->id; ?></td>
                            <td class="d-none hidden_body"><?php echo $post->body; ?></td>
                            <td class="d-none hidden_category_id"><?php echo $post->category_id; ?></td>
                            <td class="d-none hidden_sub_category_id"><?php echo $post->sub_category_id; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="/public/js/mypage_index.js"></script>
