<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2 sidebar_mypage bg-gray px-0">
            <?php $this->partial("partial/sidebar_mypage"); ?>
        </div>

        <div class="col-sm-10 main_part" data-page="sub_category">
            <div class="border-b mb-5">
                <h2><?php echo $t->_('SubCategory'); ?></h2>
            </div>
            <table id="post_table" class="table">
                <thead>
                    <tr>
                        <th><?php echo $t->_('Title'); ?></th>
                        <th><?php echo $t->_('Edit'); ?></th>
                        <th><?php echo $t->_('Category'); ?></th>
                        <th><?php echo $t->_('SubCategory'); ?></th>
                        <th><?php echo $t->_('Created'); ?></th>
                        <!-- 記事編集モーダル用データ -->
                        <th class="d-none"><?php echo $t->_('Id'); ?></th>
                        <th class="d-none"><?php echo $t->_('Body'); ?></th>
                        <th class="d-none"><?php echo $t->_('Category Id'); ?></th>
                        <th class="d-none"><?php echo $t->_('SubCategory Id'); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($posts as $post): ?>
                        <tr>
                            <td class="title"><?php echo $post->title; ?></td>
                            <td>
                                <button data-toggle="modal" data-target="#edit_post_modal" id="<?php echo $post->id; ?>" class="edit_post btn btn-primary btn-xs">
                                    <?php echo $t->_('Edit'); ?>
                                </button>
                            </td>
                            <td><?php echo $post->getCategories()->category_name; ?></td>
                            <td><?php echo $post->getSubCategories()->sub_category_name; ?></td>
                            <td><?php echo $post->created; ?></td>
                            <!-- 記事編集モーダル用データ -->
                            <td class="d-none hidden_id"><?php echo $post->id; ?></td>
                            <td class="d-none hidden_body"><?php echo $post->body; ?></td>
                            <td class="d-none hidden_category_id"><?php echo $post->category_id; ?></td>
                            <td class="d-none hidden_sub_category_id"><?php echo $post->sub_category_id; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="/public/js/mypage_index.js"></script>
